workflows:
  react-native-ios:
    name: React Native iOS build
    max_build_duration: 120
    environment:
      node: 18
      yarn: true
      cocoapods: default
      xcode: latest
      vars:
        APP_BUNDLE_ID: com.example.yourapp
        APP_NAME: "YourApp"
        XCODE_SCHEME: YourApp
        XCODE_PROJECT: ios/YourApp.xcworkspace
      flutter: none

    scripts:
      - name: Install JS dependencies
        script: |
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      - name: Install CocoaPods (iOS native deps)
        script: |
          cd ios || exit 1
          pod install --repo-update || true
          cd ..

      - name: Bundle JS for iOS (React Native)
        script: |
          npx react-native bundle --platform ios --dev false --entry-file index.js \
            --bundle-output ios/main.jsbundle --assets-dest ios

     